///<reference path='../typings/bundle.d.ts' />
exports.utils = require('./overworld/utils/utils');
exports.mixinFor = require('./overworld/utils/mixin-for');
exports.Portal = require('./overworld/portal');
exports.World = require('./overworld/world');
exports.setReact = exports.utils.setReact;
exports.aliasForMixin = exports.utils.aliasForMixin;
exports.mixinAliasMap = exports.utils.mixinAliasMap;
/*import OverworldStatic = require('./overworld/interfaces/overworld');*/
/*var Overworld:OverworldStatic = {Portal: Portal, World: World, setReact: utils.setReact, mixinFor: mixinFor};*/
